// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/ftrace/cma.proto

package perfetto.protos;

public final class Cma {
  private Cma() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CmaAllocStartFtraceEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.CmaAllocStartFtraceEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 align = 1;</code>
     * @return Whether the align field is set.
     */
    boolean hasAlign();
    /**
     * <code>optional uint32 align = 1;</code>
     * @return The align.
     */
    int getAlign();

    /**
     * <code>optional uint32 count = 2;</code>
     * @return Whether the count field is set.
     */
    boolean hasCount();
    /**
     * <code>optional uint32 count = 2;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>optional string name = 3;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code perfetto.protos.CmaAllocStartFtraceEvent}
   */
  public static final class CmaAllocStartFtraceEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.CmaAllocStartFtraceEvent)
      CmaAllocStartFtraceEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmaAllocStartFtraceEvent.newBuilder() to construct.
    private CmaAllocStartFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmaAllocStartFtraceEvent() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmaAllocStartFtraceEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocStartFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Cma.CmaAllocStartFtraceEvent.class, perfetto.protos.Cma.CmaAllocStartFtraceEvent.Builder.class);
    }

    private int bitField0_;
    public static final int ALIGN_FIELD_NUMBER = 1;
    private int align_ = 0;
    /**
     * <code>optional uint32 align = 1;</code>
     * @return Whether the align field is set.
     */
    @java.lang.Override
    public boolean hasAlign() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 align = 1;</code>
     * @return The align.
     */
    @java.lang.Override
    public int getAlign() {
      return align_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_ = 0;
    /**
     * <code>optional uint32 count = 2;</code>
     * @return Whether the count field is set.
     */
    @java.lang.Override
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>optional string name = 3;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, align_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, align_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.Cma.CmaAllocStartFtraceEvent)) {
        return super.equals(obj);
      }
      perfetto.protos.Cma.CmaAllocStartFtraceEvent other = (perfetto.protos.Cma.CmaAllocStartFtraceEvent) obj;

      if (hasAlign() != other.hasAlign()) return false;
      if (hasAlign()) {
        if (getAlign()
            != other.getAlign()) return false;
      }
      if (hasCount() != other.hasCount()) return false;
      if (hasCount()) {
        if (getCount()
            != other.getCount()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAlign()) {
        hash = (37 * hash) + ALIGN_FIELD_NUMBER;
        hash = (53 * hash) + getAlign();
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getCount();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.Cma.CmaAllocStartFtraceEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfetto.protos.CmaAllocStartFtraceEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.CmaAllocStartFtraceEvent)
        perfetto.protos.Cma.CmaAllocStartFtraceEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocStartFtraceEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.Cma.CmaAllocStartFtraceEvent.class, perfetto.protos.Cma.CmaAllocStartFtraceEvent.Builder.class);
      }

      // Construct using perfetto.protos.Cma.CmaAllocStartFtraceEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        align_ = 0;
        count_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocStartFtraceEvent getDefaultInstanceForType() {
        return perfetto.protos.Cma.CmaAllocStartFtraceEvent.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocStartFtraceEvent build() {
        perfetto.protos.Cma.CmaAllocStartFtraceEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocStartFtraceEvent buildPartial() {
        perfetto.protos.Cma.CmaAllocStartFtraceEvent result = new perfetto.protos.Cma.CmaAllocStartFtraceEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(perfetto.protos.Cma.CmaAllocStartFtraceEvent result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.align_ = align_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.count_ = count_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.Cma.CmaAllocStartFtraceEvent) {
          return mergeFrom((perfetto.protos.Cma.CmaAllocStartFtraceEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.Cma.CmaAllocStartFtraceEvent other) {
        if (other == perfetto.protos.Cma.CmaAllocStartFtraceEvent.getDefaultInstance()) return this;
        if (other.hasAlign()) {
          setAlign(other.getAlign());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                align_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                count_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int align_ ;
      /**
       * <code>optional uint32 align = 1;</code>
       * @return Whether the align field is set.
       */
      @java.lang.Override
      public boolean hasAlign() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @return The align.
       */
      @java.lang.Override
      public int getAlign() {
        return align_;
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @param value The align to set.
       * @return This builder for chaining.
       */
      public Builder setAlign(int value) {
        
        align_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlign() {
        bitField0_ = (bitField0_ & ~0x00000001);
        align_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional uint32 count = 2;</code>
       * @return Whether the count field is set.
       */
      @java.lang.Override
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.CmaAllocStartFtraceEvent)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.CmaAllocStartFtraceEvent)
    private static final perfetto.protos.Cma.CmaAllocStartFtraceEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.Cma.CmaAllocStartFtraceEvent();
    }

    public static perfetto.protos.Cma.CmaAllocStartFtraceEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CmaAllocStartFtraceEvent>
        PARSER = new com.google.protobuf.AbstractParser<CmaAllocStartFtraceEvent>() {
      @java.lang.Override
      public CmaAllocStartFtraceEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CmaAllocStartFtraceEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmaAllocStartFtraceEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.Cma.CmaAllocStartFtraceEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CmaAllocInfoFtraceEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.CmaAllocInfoFtraceEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 align = 1;</code>
     * @return Whether the align field is set.
     */
    boolean hasAlign();
    /**
     * <code>optional uint32 align = 1;</code>
     * @return The align.
     */
    int getAlign();

    /**
     * <code>optional uint32 count = 2;</code>
     * @return Whether the count field is set.
     */
    boolean hasCount();
    /**
     * <code>optional uint32 count = 2;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>optional uint32 err_iso = 3;</code>
     * @return Whether the errIso field is set.
     */
    boolean hasErrIso();
    /**
     * <code>optional uint32 err_iso = 3;</code>
     * @return The errIso.
     */
    int getErrIso();

    /**
     * <code>optional uint32 err_mig = 4;</code>
     * @return Whether the errMig field is set.
     */
    boolean hasErrMig();
    /**
     * <code>optional uint32 err_mig = 4;</code>
     * @return The errMig.
     */
    int getErrMig();

    /**
     * <code>optional uint32 err_test = 5;</code>
     * @return Whether the errTest field is set.
     */
    boolean hasErrTest();
    /**
     * <code>optional uint32 err_test = 5;</code>
     * @return The errTest.
     */
    int getErrTest();

    /**
     * <code>optional string name = 6;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 6;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 6;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional uint64 nr_mapped = 7;</code>
     * @return Whether the nrMapped field is set.
     */
    boolean hasNrMapped();
    /**
     * <code>optional uint64 nr_mapped = 7;</code>
     * @return The nrMapped.
     */
    long getNrMapped();

    /**
     * <code>optional uint64 nr_migrated = 8;</code>
     * @return Whether the nrMigrated field is set.
     */
    boolean hasNrMigrated();
    /**
     * <code>optional uint64 nr_migrated = 8;</code>
     * @return The nrMigrated.
     */
    long getNrMigrated();

    /**
     * <code>optional uint64 nr_reclaimed = 9;</code>
     * @return Whether the nrReclaimed field is set.
     */
    boolean hasNrReclaimed();
    /**
     * <code>optional uint64 nr_reclaimed = 9;</code>
     * @return The nrReclaimed.
     */
    long getNrReclaimed();

    /**
     * <code>optional uint64 pfn = 10;</code>
     * @return Whether the pfn field is set.
     */
    boolean hasPfn();
    /**
     * <code>optional uint64 pfn = 10;</code>
     * @return The pfn.
     */
    long getPfn();
  }
  /**
   * Protobuf type {@code perfetto.protos.CmaAllocInfoFtraceEvent}
   */
  public static final class CmaAllocInfoFtraceEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.CmaAllocInfoFtraceEvent)
      CmaAllocInfoFtraceEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmaAllocInfoFtraceEvent.newBuilder() to construct.
    private CmaAllocInfoFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmaAllocInfoFtraceEvent() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmaAllocInfoFtraceEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Cma.CmaAllocInfoFtraceEvent.class, perfetto.protos.Cma.CmaAllocInfoFtraceEvent.Builder.class);
    }

    private int bitField0_;
    public static final int ALIGN_FIELD_NUMBER = 1;
    private int align_ = 0;
    /**
     * <code>optional uint32 align = 1;</code>
     * @return Whether the align field is set.
     */
    @java.lang.Override
    public boolean hasAlign() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 align = 1;</code>
     * @return The align.
     */
    @java.lang.Override
    public int getAlign() {
      return align_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_ = 0;
    /**
     * <code>optional uint32 count = 2;</code>
     * @return Whether the count field is set.
     */
    @java.lang.Override
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int ERR_ISO_FIELD_NUMBER = 3;
    private int errIso_ = 0;
    /**
     * <code>optional uint32 err_iso = 3;</code>
     * @return Whether the errIso field is set.
     */
    @java.lang.Override
    public boolean hasErrIso() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 err_iso = 3;</code>
     * @return The errIso.
     */
    @java.lang.Override
    public int getErrIso() {
      return errIso_;
    }

    public static final int ERR_MIG_FIELD_NUMBER = 4;
    private int errMig_ = 0;
    /**
     * <code>optional uint32 err_mig = 4;</code>
     * @return Whether the errMig field is set.
     */
    @java.lang.Override
    public boolean hasErrMig() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 err_mig = 4;</code>
     * @return The errMig.
     */
    @java.lang.Override
    public int getErrMig() {
      return errMig_;
    }

    public static final int ERR_TEST_FIELD_NUMBER = 5;
    private int errTest_ = 0;
    /**
     * <code>optional uint32 err_test = 5;</code>
     * @return Whether the errTest field is set.
     */
    @java.lang.Override
    public boolean hasErrTest() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 err_test = 5;</code>
     * @return The errTest.
     */
    @java.lang.Override
    public int getErrTest() {
      return errTest_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>optional string name = 6;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string name = 6;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 6;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NR_MAPPED_FIELD_NUMBER = 7;
    private long nrMapped_ = 0L;
    /**
     * <code>optional uint64 nr_mapped = 7;</code>
     * @return Whether the nrMapped field is set.
     */
    @java.lang.Override
    public boolean hasNrMapped() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 nr_mapped = 7;</code>
     * @return The nrMapped.
     */
    @java.lang.Override
    public long getNrMapped() {
      return nrMapped_;
    }

    public static final int NR_MIGRATED_FIELD_NUMBER = 8;
    private long nrMigrated_ = 0L;
    /**
     * <code>optional uint64 nr_migrated = 8;</code>
     * @return Whether the nrMigrated field is set.
     */
    @java.lang.Override
    public boolean hasNrMigrated() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint64 nr_migrated = 8;</code>
     * @return The nrMigrated.
     */
    @java.lang.Override
    public long getNrMigrated() {
      return nrMigrated_;
    }

    public static final int NR_RECLAIMED_FIELD_NUMBER = 9;
    private long nrReclaimed_ = 0L;
    /**
     * <code>optional uint64 nr_reclaimed = 9;</code>
     * @return Whether the nrReclaimed field is set.
     */
    @java.lang.Override
    public boolean hasNrReclaimed() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional uint64 nr_reclaimed = 9;</code>
     * @return The nrReclaimed.
     */
    @java.lang.Override
    public long getNrReclaimed() {
      return nrReclaimed_;
    }

    public static final int PFN_FIELD_NUMBER = 10;
    private long pfn_ = 0L;
    /**
     * <code>optional uint64 pfn = 10;</code>
     * @return Whether the pfn field is set.
     */
    @java.lang.Override
    public boolean hasPfn() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional uint64 pfn = 10;</code>
     * @return The pfn.
     */
    @java.lang.Override
    public long getPfn() {
      return pfn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, align_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, errIso_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, errMig_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, errTest_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt64(7, nrMapped_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt64(8, nrMigrated_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeUInt64(9, nrReclaimed_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeUInt64(10, pfn_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, align_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, errIso_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, errMig_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, errTest_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, nrMapped_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, nrMigrated_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, nrReclaimed_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, pfn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.Cma.CmaAllocInfoFtraceEvent)) {
        return super.equals(obj);
      }
      perfetto.protos.Cma.CmaAllocInfoFtraceEvent other = (perfetto.protos.Cma.CmaAllocInfoFtraceEvent) obj;

      if (hasAlign() != other.hasAlign()) return false;
      if (hasAlign()) {
        if (getAlign()
            != other.getAlign()) return false;
      }
      if (hasCount() != other.hasCount()) return false;
      if (hasCount()) {
        if (getCount()
            != other.getCount()) return false;
      }
      if (hasErrIso() != other.hasErrIso()) return false;
      if (hasErrIso()) {
        if (getErrIso()
            != other.getErrIso()) return false;
      }
      if (hasErrMig() != other.hasErrMig()) return false;
      if (hasErrMig()) {
        if (getErrMig()
            != other.getErrMig()) return false;
      }
      if (hasErrTest() != other.hasErrTest()) return false;
      if (hasErrTest()) {
        if (getErrTest()
            != other.getErrTest()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasNrMapped() != other.hasNrMapped()) return false;
      if (hasNrMapped()) {
        if (getNrMapped()
            != other.getNrMapped()) return false;
      }
      if (hasNrMigrated() != other.hasNrMigrated()) return false;
      if (hasNrMigrated()) {
        if (getNrMigrated()
            != other.getNrMigrated()) return false;
      }
      if (hasNrReclaimed() != other.hasNrReclaimed()) return false;
      if (hasNrReclaimed()) {
        if (getNrReclaimed()
            != other.getNrReclaimed()) return false;
      }
      if (hasPfn() != other.hasPfn()) return false;
      if (hasPfn()) {
        if (getPfn()
            != other.getPfn()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAlign()) {
        hash = (37 * hash) + ALIGN_FIELD_NUMBER;
        hash = (53 * hash) + getAlign();
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getCount();
      }
      if (hasErrIso()) {
        hash = (37 * hash) + ERR_ISO_FIELD_NUMBER;
        hash = (53 * hash) + getErrIso();
      }
      if (hasErrMig()) {
        hash = (37 * hash) + ERR_MIG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMig();
      }
      if (hasErrTest()) {
        hash = (37 * hash) + ERR_TEST_FIELD_NUMBER;
        hash = (53 * hash) + getErrTest();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasNrMapped()) {
        hash = (37 * hash) + NR_MAPPED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNrMapped());
      }
      if (hasNrMigrated()) {
        hash = (37 * hash) + NR_MIGRATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNrMigrated());
      }
      if (hasNrReclaimed()) {
        hash = (37 * hash) + NR_RECLAIMED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNrReclaimed());
      }
      if (hasPfn()) {
        hash = (37 * hash) + PFN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPfn());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.Cma.CmaAllocInfoFtraceEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfetto.protos.CmaAllocInfoFtraceEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.CmaAllocInfoFtraceEvent)
        perfetto.protos.Cma.CmaAllocInfoFtraceEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.Cma.CmaAllocInfoFtraceEvent.class, perfetto.protos.Cma.CmaAllocInfoFtraceEvent.Builder.class);
      }

      // Construct using perfetto.protos.Cma.CmaAllocInfoFtraceEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        align_ = 0;
        count_ = 0;
        errIso_ = 0;
        errMig_ = 0;
        errTest_ = 0;
        name_ = "";
        nrMapped_ = 0L;
        nrMigrated_ = 0L;
        nrReclaimed_ = 0L;
        pfn_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.Cma.internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocInfoFtraceEvent getDefaultInstanceForType() {
        return perfetto.protos.Cma.CmaAllocInfoFtraceEvent.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocInfoFtraceEvent build() {
        perfetto.protos.Cma.CmaAllocInfoFtraceEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.Cma.CmaAllocInfoFtraceEvent buildPartial() {
        perfetto.protos.Cma.CmaAllocInfoFtraceEvent result = new perfetto.protos.Cma.CmaAllocInfoFtraceEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(perfetto.protos.Cma.CmaAllocInfoFtraceEvent result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.align_ = align_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.count_ = count_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errIso_ = errIso_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.errMig_ = errMig_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.errTest_ = errTest_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.nrMapped_ = nrMapped_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.nrMigrated_ = nrMigrated_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.nrReclaimed_ = nrReclaimed_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.pfn_ = pfn_;
          to_bitField0_ |= 0x00000200;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.Cma.CmaAllocInfoFtraceEvent) {
          return mergeFrom((perfetto.protos.Cma.CmaAllocInfoFtraceEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.Cma.CmaAllocInfoFtraceEvent other) {
        if (other == perfetto.protos.Cma.CmaAllocInfoFtraceEvent.getDefaultInstance()) return this;
        if (other.hasAlign()) {
          setAlign(other.getAlign());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasErrIso()) {
          setErrIso(other.getErrIso());
        }
        if (other.hasErrMig()) {
          setErrMig(other.getErrMig());
        }
        if (other.hasErrTest()) {
          setErrTest(other.getErrTest());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasNrMapped()) {
          setNrMapped(other.getNrMapped());
        }
        if (other.hasNrMigrated()) {
          setNrMigrated(other.getNrMigrated());
        }
        if (other.hasNrReclaimed()) {
          setNrReclaimed(other.getNrReclaimed());
        }
        if (other.hasPfn()) {
          setPfn(other.getPfn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                align_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                count_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                errIso_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                errMig_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                errTest_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                nrMapped_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                nrMigrated_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                nrReclaimed_ = input.readUInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                pfn_ = input.readUInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int align_ ;
      /**
       * <code>optional uint32 align = 1;</code>
       * @return Whether the align field is set.
       */
      @java.lang.Override
      public boolean hasAlign() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @return The align.
       */
      @java.lang.Override
      public int getAlign() {
        return align_;
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @param value The align to set.
       * @return This builder for chaining.
       */
      public Builder setAlign(int value) {
        
        align_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 align = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlign() {
        bitField0_ = (bitField0_ & ~0x00000001);
        align_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional uint32 count = 2;</code>
       * @return Whether the count field is set.
       */
      @java.lang.Override
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      private int errIso_ ;
      /**
       * <code>optional uint32 err_iso = 3;</code>
       * @return Whether the errIso field is set.
       */
      @java.lang.Override
      public boolean hasErrIso() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 err_iso = 3;</code>
       * @return The errIso.
       */
      @java.lang.Override
      public int getErrIso() {
        return errIso_;
      }
      /**
       * <code>optional uint32 err_iso = 3;</code>
       * @param value The errIso to set.
       * @return This builder for chaining.
       */
      public Builder setErrIso(int value) {
        
        errIso_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 err_iso = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrIso() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errIso_ = 0;
        onChanged();
        return this;
      }

      private int errMig_ ;
      /**
       * <code>optional uint32 err_mig = 4;</code>
       * @return Whether the errMig field is set.
       */
      @java.lang.Override
      public boolean hasErrMig() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 err_mig = 4;</code>
       * @return The errMig.
       */
      @java.lang.Override
      public int getErrMig() {
        return errMig_;
      }
      /**
       * <code>optional uint32 err_mig = 4;</code>
       * @param value The errMig to set.
       * @return This builder for chaining.
       */
      public Builder setErrMig(int value) {
        
        errMig_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 err_mig = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrMig() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errMig_ = 0;
        onChanged();
        return this;
      }

      private int errTest_ ;
      /**
       * <code>optional uint32 err_test = 5;</code>
       * @return Whether the errTest field is set.
       */
      @java.lang.Override
      public boolean hasErrTest() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint32 err_test = 5;</code>
       * @return The errTest.
       */
      @java.lang.Override
      public int getErrTest() {
        return errTest_;
      }
      /**
       * <code>optional uint32 err_test = 5;</code>
       * @param value The errTest to set.
       * @return This builder for chaining.
       */
      public Builder setErrTest(int value) {
        
        errTest_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 err_test = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrTest() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errTest_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 6;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string name = 6;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private long nrMapped_ ;
      /**
       * <code>optional uint64 nr_mapped = 7;</code>
       * @return Whether the nrMapped field is set.
       */
      @java.lang.Override
      public boolean hasNrMapped() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint64 nr_mapped = 7;</code>
       * @return The nrMapped.
       */
      @java.lang.Override
      public long getNrMapped() {
        return nrMapped_;
      }
      /**
       * <code>optional uint64 nr_mapped = 7;</code>
       * @param value The nrMapped to set.
       * @return This builder for chaining.
       */
      public Builder setNrMapped(long value) {
        
        nrMapped_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 nr_mapped = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNrMapped() {
        bitField0_ = (bitField0_ & ~0x00000040);
        nrMapped_ = 0L;
        onChanged();
        return this;
      }

      private long nrMigrated_ ;
      /**
       * <code>optional uint64 nr_migrated = 8;</code>
       * @return Whether the nrMigrated field is set.
       */
      @java.lang.Override
      public boolean hasNrMigrated() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional uint64 nr_migrated = 8;</code>
       * @return The nrMigrated.
       */
      @java.lang.Override
      public long getNrMigrated() {
        return nrMigrated_;
      }
      /**
       * <code>optional uint64 nr_migrated = 8;</code>
       * @param value The nrMigrated to set.
       * @return This builder for chaining.
       */
      public Builder setNrMigrated(long value) {
        
        nrMigrated_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 nr_migrated = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNrMigrated() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nrMigrated_ = 0L;
        onChanged();
        return this;
      }

      private long nrReclaimed_ ;
      /**
       * <code>optional uint64 nr_reclaimed = 9;</code>
       * @return Whether the nrReclaimed field is set.
       */
      @java.lang.Override
      public boolean hasNrReclaimed() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional uint64 nr_reclaimed = 9;</code>
       * @return The nrReclaimed.
       */
      @java.lang.Override
      public long getNrReclaimed() {
        return nrReclaimed_;
      }
      /**
       * <code>optional uint64 nr_reclaimed = 9;</code>
       * @param value The nrReclaimed to set.
       * @return This builder for chaining.
       */
      public Builder setNrReclaimed(long value) {
        
        nrReclaimed_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 nr_reclaimed = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearNrReclaimed() {
        bitField0_ = (bitField0_ & ~0x00000100);
        nrReclaimed_ = 0L;
        onChanged();
        return this;
      }

      private long pfn_ ;
      /**
       * <code>optional uint64 pfn = 10;</code>
       * @return Whether the pfn field is set.
       */
      @java.lang.Override
      public boolean hasPfn() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional uint64 pfn = 10;</code>
       * @return The pfn.
       */
      @java.lang.Override
      public long getPfn() {
        return pfn_;
      }
      /**
       * <code>optional uint64 pfn = 10;</code>
       * @param value The pfn to set.
       * @return This builder for chaining.
       */
      public Builder setPfn(long value) {
        
        pfn_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 pfn = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPfn() {
        bitField0_ = (bitField0_ & ~0x00000200);
        pfn_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.CmaAllocInfoFtraceEvent)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.CmaAllocInfoFtraceEvent)
    private static final perfetto.protos.Cma.CmaAllocInfoFtraceEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.Cma.CmaAllocInfoFtraceEvent();
    }

    public static perfetto.protos.Cma.CmaAllocInfoFtraceEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CmaAllocInfoFtraceEvent>
        PARSER = new com.google.protobuf.AbstractParser<CmaAllocInfoFtraceEvent>() {
      @java.lang.Override
      public CmaAllocInfoFtraceEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CmaAllocInfoFtraceEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmaAllocInfoFtraceEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.Cma.CmaAllocInfoFtraceEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_CmaAllocStartFtraceEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&protos/perfetto/trace/ftrace/cma.proto" +
      "\022\017perfetto.protos\"F\n\030CmaAllocStartFtrace" +
      "Event\022\r\n\005align\030\001 \001(\r\022\r\n\005count\030\002 \001(\r\022\014\n\004n" +
      "ame\030\003 \001(\t\"\304\001\n\027CmaAllocInfoFtraceEvent\022\r\n" +
      "\005align\030\001 \001(\r\022\r\n\005count\030\002 \001(\r\022\017\n\007err_iso\030\003" +
      " \001(\r\022\017\n\007err_mig\030\004 \001(\r\022\020\n\010err_test\030\005 \001(\r\022" +
      "\014\n\004name\030\006 \001(\t\022\021\n\tnr_mapped\030\007 \001(\004\022\023\n\013nr_m" +
      "igrated\030\010 \001(\004\022\024\n\014nr_reclaimed\030\t \001(\004\022\013\n\003p" +
      "fn\030\n \001(\004"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_CmaAllocStartFtraceEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_CmaAllocStartFtraceEvent_descriptor,
        new java.lang.String[] { "Align", "Count", "Name", });
    internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_CmaAllocInfoFtraceEvent_descriptor,
        new java.lang.String[] { "Align", "Count", "ErrIso", "ErrMig", "ErrTest", "Name", "NrMapped", "NrMigrated", "NrReclaimed", "Pfn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
