// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/metrics/chrome/slice_names.proto

package perfetto.protos;

public final class SliceNames {
  private SliceNames() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChromeSliceNamesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.ChromeSliceNames)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @return A list containing the chromeVersionCode.
     */
    java.util.List<java.lang.Long> getChromeVersionCodeList();
    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @return The count of chromeVersionCode.
     */
    int getChromeVersionCodeCount();
    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @param index The index of the element to return.
     * @return The chromeVersionCode at the given index.
     */
    long getChromeVersionCode(int index);

    /**
     * <code>repeated string slice_name = 2;</code>
     * @return A list containing the sliceName.
     */
    java.util.List<java.lang.String>
        getSliceNameList();
    /**
     * <code>repeated string slice_name = 2;</code>
     * @return The count of sliceName.
     */
    int getSliceNameCount();
    /**
     * <code>repeated string slice_name = 2;</code>
     * @param index The index of the element to return.
     * @return The sliceName at the given index.
     */
    java.lang.String getSliceName(int index);
    /**
     * <code>repeated string slice_name = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sliceName at the given index.
     */
    com.google.protobuf.ByteString
        getSliceNameBytes(int index);
  }
  /**
   * <pre>
   * The list of slice names in a trace.
   * Use cases include deobfuscating slice names by getting this list,
   * generating, and prepending a translation table to the trace.
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.ChromeSliceNames}
   */
  public static final class ChromeSliceNames extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.ChromeSliceNames)
      ChromeSliceNamesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChromeSliceNames.newBuilder() to construct.
    private ChromeSliceNames(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChromeSliceNames() {
      chromeVersionCode_ = emptyLongList();
      sliceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChromeSliceNames();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.SliceNames.internal_static_perfetto_protos_ChromeSliceNames_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.SliceNames.internal_static_perfetto_protos_ChromeSliceNames_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.SliceNames.ChromeSliceNames.class, perfetto.protos.SliceNames.ChromeSliceNames.Builder.class);
    }

    public static final int CHROME_VERSION_CODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList chromeVersionCode_;
    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @return A list containing the chromeVersionCode.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getChromeVersionCodeList() {
      return chromeVersionCode_;
    }
    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @return The count of chromeVersionCode.
     */
    public int getChromeVersionCodeCount() {
      return chromeVersionCode_.size();
    }
    /**
     * <code>repeated int64 chrome_version_code = 1;</code>
     * @param index The index of the element to return.
     * @return The chromeVersionCode at the given index.
     */
    public long getChromeVersionCode(int index) {
      return chromeVersionCode_.getLong(index);
    }

    public static final int SLICE_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList sliceName_;
    /**
     * <code>repeated string slice_name = 2;</code>
     * @return A list containing the sliceName.
     */
    public com.google.protobuf.ProtocolStringList
        getSliceNameList() {
      return sliceName_;
    }
    /**
     * <code>repeated string slice_name = 2;</code>
     * @return The count of sliceName.
     */
    public int getSliceNameCount() {
      return sliceName_.size();
    }
    /**
     * <code>repeated string slice_name = 2;</code>
     * @param index The index of the element to return.
     * @return The sliceName at the given index.
     */
    public java.lang.String getSliceName(int index) {
      return sliceName_.get(index);
    }
    /**
     * <code>repeated string slice_name = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sliceName at the given index.
     */
    public com.google.protobuf.ByteString
        getSliceNameBytes(int index) {
      return sliceName_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < chromeVersionCode_.size(); i++) {
        output.writeInt64(1, chromeVersionCode_.getLong(i));
      }
      for (int i = 0; i < sliceName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sliceName_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < chromeVersionCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(chromeVersionCode_.getLong(i));
        }
        size += dataSize;
        size += 1 * getChromeVersionCodeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sliceName_.size(); i++) {
          dataSize += computeStringSizeNoTag(sliceName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSliceNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.SliceNames.ChromeSliceNames)) {
        return super.equals(obj);
      }
      perfetto.protos.SliceNames.ChromeSliceNames other = (perfetto.protos.SliceNames.ChromeSliceNames) obj;

      if (!getChromeVersionCodeList()
          .equals(other.getChromeVersionCodeList())) return false;
      if (!getSliceNameList()
          .equals(other.getSliceNameList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChromeVersionCodeCount() > 0) {
        hash = (37 * hash) + CHROME_VERSION_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getChromeVersionCodeList().hashCode();
      }
      if (getSliceNameCount() > 0) {
        hash = (37 * hash) + SLICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSliceNameList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.SliceNames.ChromeSliceNames parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.SliceNames.ChromeSliceNames prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The list of slice names in a trace.
     * Use cases include deobfuscating slice names by getting this list,
     * generating, and prepending a translation table to the trace.
     * </pre>
     *
     * Protobuf type {@code perfetto.protos.ChromeSliceNames}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.ChromeSliceNames)
        perfetto.protos.SliceNames.ChromeSliceNamesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.SliceNames.internal_static_perfetto_protos_ChromeSliceNames_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.SliceNames.internal_static_perfetto_protos_ChromeSliceNames_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.SliceNames.ChromeSliceNames.class, perfetto.protos.SliceNames.ChromeSliceNames.Builder.class);
      }

      // Construct using perfetto.protos.SliceNames.ChromeSliceNames.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        chromeVersionCode_ = emptyLongList();
        sliceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.SliceNames.internal_static_perfetto_protos_ChromeSliceNames_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.SliceNames.ChromeSliceNames getDefaultInstanceForType() {
        return perfetto.protos.SliceNames.ChromeSliceNames.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.SliceNames.ChromeSliceNames build() {
        perfetto.protos.SliceNames.ChromeSliceNames result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.SliceNames.ChromeSliceNames buildPartial() {
        perfetto.protos.SliceNames.ChromeSliceNames result = new perfetto.protos.SliceNames.ChromeSliceNames(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(perfetto.protos.SliceNames.ChromeSliceNames result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          chromeVersionCode_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chromeVersionCode_ = chromeVersionCode_;
        if (((bitField0_ & 0x00000002) != 0)) {
          sliceName_ = sliceName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sliceName_ = sliceName_;
      }

      private void buildPartial0(perfetto.protos.SliceNames.ChromeSliceNames result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.SliceNames.ChromeSliceNames) {
          return mergeFrom((perfetto.protos.SliceNames.ChromeSliceNames)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.SliceNames.ChromeSliceNames other) {
        if (other == perfetto.protos.SliceNames.ChromeSliceNames.getDefaultInstance()) return this;
        if (!other.chromeVersionCode_.isEmpty()) {
          if (chromeVersionCode_.isEmpty()) {
            chromeVersionCode_ = other.chromeVersionCode_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChromeVersionCodeIsMutable();
            chromeVersionCode_.addAll(other.chromeVersionCode_);
          }
          onChanged();
        }
        if (!other.sliceName_.isEmpty()) {
          if (sliceName_.isEmpty()) {
            sliceName_ = other.sliceName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSliceNameIsMutable();
            sliceName_.addAll(other.sliceName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                long v = input.readInt64();
                ensureChromeVersionCodeIsMutable();
                chromeVersionCode_.addLong(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureChromeVersionCodeIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  chromeVersionCode_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                ensureSliceNameIsMutable();
                sliceName_.add(bs);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList chromeVersionCode_ = emptyLongList();
      private void ensureChromeVersionCodeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          chromeVersionCode_ = mutableCopy(chromeVersionCode_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @return A list containing the chromeVersionCode.
       */
      public java.util.List<java.lang.Long>
          getChromeVersionCodeList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(chromeVersionCode_) : chromeVersionCode_;
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @return The count of chromeVersionCode.
       */
      public int getChromeVersionCodeCount() {
        return chromeVersionCode_.size();
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @param index The index of the element to return.
       * @return The chromeVersionCode at the given index.
       */
      public long getChromeVersionCode(int index) {
        return chromeVersionCode_.getLong(index);
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @param index The index to set the value at.
       * @param value The chromeVersionCode to set.
       * @return This builder for chaining.
       */
      public Builder setChromeVersionCode(
          int index, long value) {
        
        ensureChromeVersionCodeIsMutable();
        chromeVersionCode_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @param value The chromeVersionCode to add.
       * @return This builder for chaining.
       */
      public Builder addChromeVersionCode(long value) {
        
        ensureChromeVersionCodeIsMutable();
        chromeVersionCode_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @param values The chromeVersionCode to add.
       * @return This builder for chaining.
       */
      public Builder addAllChromeVersionCode(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureChromeVersionCodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chromeVersionCode_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chrome_version_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChromeVersionCode() {
        chromeVersionCode_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList sliceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSliceNameIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          sliceName_ = new com.google.protobuf.LazyStringArrayList(sliceName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @return A list containing the sliceName.
       */
      public com.google.protobuf.ProtocolStringList
          getSliceNameList() {
        return sliceName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @return The count of sliceName.
       */
      public int getSliceNameCount() {
        return sliceName_.size();
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param index The index of the element to return.
       * @return The sliceName at the given index.
       */
      public java.lang.String getSliceName(int index) {
        return sliceName_.get(index);
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sliceName at the given index.
       */
      public com.google.protobuf.ByteString
          getSliceNameBytes(int index) {
        return sliceName_.getByteString(index);
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param index The index to set the value at.
       * @param value The sliceName to set.
       * @return This builder for chaining.
       */
      public Builder setSliceName(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSliceNameIsMutable();
        sliceName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param value The sliceName to add.
       * @return This builder for chaining.
       */
      public Builder addSliceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSliceNameIsMutable();
        sliceName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param values The sliceName to add.
       * @return This builder for chaining.
       */
      public Builder addAllSliceName(
          java.lang.Iterable<java.lang.String> values) {
        ensureSliceNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sliceName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSliceName() {
        sliceName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string slice_name = 2;</code>
       * @param value The bytes of the sliceName to add.
       * @return This builder for chaining.
       */
      public Builder addSliceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSliceNameIsMutable();
        sliceName_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.ChromeSliceNames)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.ChromeSliceNames)
    private static final perfetto.protos.SliceNames.ChromeSliceNames DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.SliceNames.ChromeSliceNames();
    }

    public static perfetto.protos.SliceNames.ChromeSliceNames getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChromeSliceNames>
        PARSER = new com.google.protobuf.AbstractParser<ChromeSliceNames>() {
      @java.lang.Override
      public ChromeSliceNames parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChromeSliceNames> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChromeSliceNames> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.SliceNames.ChromeSliceNames getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_ChromeSliceNames_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_ChromeSliceNames_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0protos/perfetto/metrics/chrome/slice_n" +
      "ames.proto\022\017perfetto.protos\"C\n\020ChromeSli" +
      "ceNames\022\033\n\023chrome_version_code\030\001 \003(\003\022\022\n\n" +
      "slice_name\030\002 \003(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_ChromeSliceNames_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_ChromeSliceNames_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_ChromeSliceNames_descriptor,
        new java.lang.String[] { "ChromeVersionCode", "SliceName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
