// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/trace/ftrace/fastrpc.proto

package perfetto.protos;

public final class Fastrpc {
  private Fastrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FastrpcDmaStatFtraceEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.FastrpcDmaStatFtraceEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 cid = 1;</code>
     * @return Whether the cid field is set.
     */
    boolean hasCid();
    /**
     * <code>optional int32 cid = 1;</code>
     * @return The cid.
     */
    int getCid();

    /**
     * <code>optional int64 len = 2;</code>
     * @return Whether the len field is set.
     */
    boolean hasLen();
    /**
     * <code>optional int64 len = 2;</code>
     * @return The len.
     */
    long getLen();

    /**
     * <code>optional uint64 total_allocated = 3;</code>
     * @return Whether the totalAllocated field is set.
     */
    boolean hasTotalAllocated();
    /**
     * <code>optional uint64 total_allocated = 3;</code>
     * @return The totalAllocated.
     */
    long getTotalAllocated();
  }
  /**
   * Protobuf type {@code perfetto.protos.FastrpcDmaStatFtraceEvent}
   */
  public static final class FastrpcDmaStatFtraceEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.FastrpcDmaStatFtraceEvent)
      FastrpcDmaStatFtraceEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FastrpcDmaStatFtraceEvent.newBuilder() to construct.
    private FastrpcDmaStatFtraceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FastrpcDmaStatFtraceEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FastrpcDmaStatFtraceEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.Fastrpc.internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.Fastrpc.internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.class, perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.Builder.class);
    }

    private int bitField0_;
    public static final int CID_FIELD_NUMBER = 1;
    private int cid_ = 0;
    /**
     * <code>optional int32 cid = 1;</code>
     * @return Whether the cid field is set.
     */
    @java.lang.Override
    public boolean hasCid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 cid = 1;</code>
     * @return The cid.
     */
    @java.lang.Override
    public int getCid() {
      return cid_;
    }

    public static final int LEN_FIELD_NUMBER = 2;
    private long len_ = 0L;
    /**
     * <code>optional int64 len = 2;</code>
     * @return Whether the len field is set.
     */
    @java.lang.Override
    public boolean hasLen() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 len = 2;</code>
     * @return The len.
     */
    @java.lang.Override
    public long getLen() {
      return len_;
    }

    public static final int TOTAL_ALLOCATED_FIELD_NUMBER = 3;
    private long totalAllocated_ = 0L;
    /**
     * <code>optional uint64 total_allocated = 3;</code>
     * @return Whether the totalAllocated field is set.
     */
    @java.lang.Override
    public boolean hasTotalAllocated() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 total_allocated = 3;</code>
     * @return The totalAllocated.
     */
    @java.lang.Override
    public long getTotalAllocated() {
      return totalAllocated_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, cid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, len_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, totalAllocated_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, len_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, totalAllocated_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent)) {
        return super.equals(obj);
      }
      perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent other = (perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent) obj;

      if (hasCid() != other.hasCid()) return false;
      if (hasCid()) {
        if (getCid()
            != other.getCid()) return false;
      }
      if (hasLen() != other.hasLen()) return false;
      if (hasLen()) {
        if (getLen()
            != other.getLen()) return false;
      }
      if (hasTotalAllocated() != other.hasTotalAllocated()) return false;
      if (hasTotalAllocated()) {
        if (getTotalAllocated()
            != other.getTotalAllocated()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCid()) {
        hash = (37 * hash) + CID_FIELD_NUMBER;
        hash = (53 * hash) + getCid();
      }
      if (hasLen()) {
        hash = (37 * hash) + LEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLen());
      }
      if (hasTotalAllocated()) {
        hash = (37 * hash) + TOTAL_ALLOCATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalAllocated());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfetto.protos.FastrpcDmaStatFtraceEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.FastrpcDmaStatFtraceEvent)
        perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.Fastrpc.internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.Fastrpc.internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.class, perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.Builder.class);
      }

      // Construct using perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cid_ = 0;
        len_ = 0L;
        totalAllocated_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.Fastrpc.internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent getDefaultInstanceForType() {
        return perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent build() {
        perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent buildPartial() {
        perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent result = new perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cid_ = cid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.len_ = len_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalAllocated_ = totalAllocated_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent) {
          return mergeFrom((perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent other) {
        if (other == perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasLen()) {
          setLen(other.getLen());
        }
        if (other.hasTotalAllocated()) {
          setTotalAllocated(other.getTotalAllocated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                len_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalAllocated_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cid_ ;
      /**
       * <code>optional int32 cid = 1;</code>
       * @return Whether the cid field is set.
       */
      @java.lang.Override
      public boolean hasCid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 cid = 1;</code>
       * @return The cid.
       */
      @java.lang.Override
      public int getCid() {
        return cid_;
      }
      /**
       * <code>optional int32 cid = 1;</code>
       * @param value The cid to set.
       * @return This builder for chaining.
       */
      public Builder setCid(int value) {
        
        cid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        onChanged();
        return this;
      }

      private long len_ ;
      /**
       * <code>optional int64 len = 2;</code>
       * @return Whether the len field is set.
       */
      @java.lang.Override
      public boolean hasLen() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 len = 2;</code>
       * @return The len.
       */
      @java.lang.Override
      public long getLen() {
        return len_;
      }
      /**
       * <code>optional int64 len = 2;</code>
       * @param value The len to set.
       * @return This builder for chaining.
       */
      public Builder setLen(long value) {
        
        len_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 len = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        len_ = 0L;
        onChanged();
        return this;
      }

      private long totalAllocated_ ;
      /**
       * <code>optional uint64 total_allocated = 3;</code>
       * @return Whether the totalAllocated field is set.
       */
      @java.lang.Override
      public boolean hasTotalAllocated() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 total_allocated = 3;</code>
       * @return The totalAllocated.
       */
      @java.lang.Override
      public long getTotalAllocated() {
        return totalAllocated_;
      }
      /**
       * <code>optional uint64 total_allocated = 3;</code>
       * @param value The totalAllocated to set.
       * @return This builder for chaining.
       */
      public Builder setTotalAllocated(long value) {
        
        totalAllocated_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 total_allocated = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalAllocated() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalAllocated_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.FastrpcDmaStatFtraceEvent)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.FastrpcDmaStatFtraceEvent)
    private static final perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent();
    }

    public static perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FastrpcDmaStatFtraceEvent>
        PARSER = new com.google.protobuf.AbstractParser<FastrpcDmaStatFtraceEvent>() {
      @java.lang.Override
      public FastrpcDmaStatFtraceEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FastrpcDmaStatFtraceEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FastrpcDmaStatFtraceEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.Fastrpc.FastrpcDmaStatFtraceEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*protos/perfetto/trace/ftrace/fastrpc.p" +
      "roto\022\017perfetto.protos\"N\n\031FastrpcDmaStatF" +
      "traceEvent\022\013\n\003cid\030\001 \001(\005\022\013\n\003len\030\002 \001(\003\022\027\n\017" +
      "total_allocated\030\003 \001(\004"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_FastrpcDmaStatFtraceEvent_descriptor,
        new java.lang.String[] { "Cid", "Len", "TotalAllocated", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
