// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/metrics/chrome/performance_mark_hashes.proto

package perfetto.protos;

public final class PerformanceMarkHashes {
  private PerformanceMarkHashes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChromePerformanceMarkHashesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.ChromePerformanceMarkHashes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @return A list containing the siteHash.
     */
    java.util.List<java.lang.Long> getSiteHashList();
    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @return The count of siteHash.
     */
    int getSiteHashCount();
    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @param index The index of the element to return.
     * @return The siteHash at the given index.
     */
    long getSiteHash(int index);

    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @return A list containing the markHash.
     */
    java.util.List<java.lang.Long> getMarkHashList();
    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @return The count of markHash.
     */
    int getMarkHashCount();
    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @param index The index of the element to return.
     * @return The markHash at the given index.
     */
    long getMarkHash(int index);
  }
  /**
   * <pre>
   * The list of Chrome performance mark hashes in trace track events.
   * Use cases include translating performance mark hashes to site and mark
   * names by getting this list, and prepending a translation table to the trace.
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.ChromePerformanceMarkHashes}
   */
  public static final class ChromePerformanceMarkHashes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.ChromePerformanceMarkHashes)
      ChromePerformanceMarkHashesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChromePerformanceMarkHashes.newBuilder() to construct.
    private ChromePerformanceMarkHashes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChromePerformanceMarkHashes() {
      siteHash_ = emptyLongList();
      markHash_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChromePerformanceMarkHashes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.PerformanceMarkHashes.internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.PerformanceMarkHashes.internal_static_perfetto_protos_ChromePerformanceMarkHashes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.class, perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.Builder.class);
    }

    public static final int SITE_HASH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList siteHash_;
    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @return A list containing the siteHash.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getSiteHashList() {
      return siteHash_;
    }
    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @return The count of siteHash.
     */
    public int getSiteHashCount() {
      return siteHash_.size();
    }
    /**
     * <code>repeated int64 site_hash = 1;</code>
     * @param index The index of the element to return.
     * @return The siteHash at the given index.
     */
    public long getSiteHash(int index) {
      return siteHash_.getLong(index);
    }

    public static final int MARK_HASH_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList markHash_;
    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @return A list containing the markHash.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getMarkHashList() {
      return markHash_;
    }
    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @return The count of markHash.
     */
    public int getMarkHashCount() {
      return markHash_.size();
    }
    /**
     * <code>repeated int64 mark_hash = 2;</code>
     * @param index The index of the element to return.
     * @return The markHash at the given index.
     */
    public long getMarkHash(int index) {
      return markHash_.getLong(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < siteHash_.size(); i++) {
        output.writeInt64(1, siteHash_.getLong(i));
      }
      for (int i = 0; i < markHash_.size(); i++) {
        output.writeInt64(2, markHash_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < siteHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(siteHash_.getLong(i));
        }
        size += dataSize;
        size += 1 * getSiteHashList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < markHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(markHash_.getLong(i));
        }
        size += dataSize;
        size += 1 * getMarkHashList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes)) {
        return super.equals(obj);
      }
      perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes other = (perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes) obj;

      if (!getSiteHashList()
          .equals(other.getSiteHashList())) return false;
      if (!getMarkHashList()
          .equals(other.getMarkHashList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSiteHashCount() > 0) {
        hash = (37 * hash) + SITE_HASH_FIELD_NUMBER;
        hash = (53 * hash) + getSiteHashList().hashCode();
      }
      if (getMarkHashCount() > 0) {
        hash = (37 * hash) + MARK_HASH_FIELD_NUMBER;
        hash = (53 * hash) + getMarkHashList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The list of Chrome performance mark hashes in trace track events.
     * Use cases include translating performance mark hashes to site and mark
     * names by getting this list, and prepending a translation table to the trace.
     * </pre>
     *
     * Protobuf type {@code perfetto.protos.ChromePerformanceMarkHashes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.ChromePerformanceMarkHashes)
        perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.PerformanceMarkHashes.internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.PerformanceMarkHashes.internal_static_perfetto_protos_ChromePerformanceMarkHashes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.class, perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.Builder.class);
      }

      // Construct using perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        siteHash_ = emptyLongList();
        markHash_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.PerformanceMarkHashes.internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes getDefaultInstanceForType() {
        return perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes build() {
        perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes buildPartial() {
        perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes result = new perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          siteHash_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.siteHash_ = siteHash_;
        if (((bitField0_ & 0x00000002) != 0)) {
          markHash_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.markHash_ = markHash_;
      }

      private void buildPartial0(perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes) {
          return mergeFrom((perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes other) {
        if (other == perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes.getDefaultInstance()) return this;
        if (!other.siteHash_.isEmpty()) {
          if (siteHash_.isEmpty()) {
            siteHash_ = other.siteHash_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSiteHashIsMutable();
            siteHash_.addAll(other.siteHash_);
          }
          onChanged();
        }
        if (!other.markHash_.isEmpty()) {
          if (markHash_.isEmpty()) {
            markHash_ = other.markHash_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMarkHashIsMutable();
            markHash_.addAll(other.markHash_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                long v = input.readInt64();
                ensureSiteHashIsMutable();
                siteHash_.addLong(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureSiteHashIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  siteHash_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 16: {
                long v = input.readInt64();
                ensureMarkHashIsMutable();
                markHash_.addLong(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureMarkHashIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  markHash_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList siteHash_ = emptyLongList();
      private void ensureSiteHashIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          siteHash_ = mutableCopy(siteHash_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @return A list containing the siteHash.
       */
      public java.util.List<java.lang.Long>
          getSiteHashList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(siteHash_) : siteHash_;
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @return The count of siteHash.
       */
      public int getSiteHashCount() {
        return siteHash_.size();
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @param index The index of the element to return.
       * @return The siteHash at the given index.
       */
      public long getSiteHash(int index) {
        return siteHash_.getLong(index);
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @param index The index to set the value at.
       * @param value The siteHash to set.
       * @return This builder for chaining.
       */
      public Builder setSiteHash(
          int index, long value) {
        
        ensureSiteHashIsMutable();
        siteHash_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @param value The siteHash to add.
       * @return This builder for chaining.
       */
      public Builder addSiteHash(long value) {
        
        ensureSiteHashIsMutable();
        siteHash_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @param values The siteHash to add.
       * @return This builder for chaining.
       */
      public Builder addAllSiteHash(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSiteHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, siteHash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 site_hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSiteHash() {
        siteHash_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList markHash_ = emptyLongList();
      private void ensureMarkHashIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          markHash_ = mutableCopy(markHash_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @return A list containing the markHash.
       */
      public java.util.List<java.lang.Long>
          getMarkHashList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(markHash_) : markHash_;
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @return The count of markHash.
       */
      public int getMarkHashCount() {
        return markHash_.size();
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @param index The index of the element to return.
       * @return The markHash at the given index.
       */
      public long getMarkHash(int index) {
        return markHash_.getLong(index);
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @param index The index to set the value at.
       * @param value The markHash to set.
       * @return This builder for chaining.
       */
      public Builder setMarkHash(
          int index, long value) {
        
        ensureMarkHashIsMutable();
        markHash_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @param value The markHash to add.
       * @return This builder for chaining.
       */
      public Builder addMarkHash(long value) {
        
        ensureMarkHashIsMutable();
        markHash_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @param values The markHash to add.
       * @return This builder for chaining.
       */
      public Builder addAllMarkHash(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMarkHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, markHash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 mark_hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarkHash() {
        markHash_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.ChromePerformanceMarkHashes)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.ChromePerformanceMarkHashes)
    private static final perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes();
    }

    public static perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChromePerformanceMarkHashes>
        PARSER = new com.google.protobuf.AbstractParser<ChromePerformanceMarkHashes>() {
      @java.lang.Override
      public ChromePerformanceMarkHashes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChromePerformanceMarkHashes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChromePerformanceMarkHashes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.PerformanceMarkHashes.ChromePerformanceMarkHashes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_ChromePerformanceMarkHashes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<protos/perfetto/metrics/chrome/perform" +
      "ance_mark_hashes.proto\022\017perfetto.protos\"" +
      "C\n\033ChromePerformanceMarkHashes\022\021\n\tsite_h" +
      "ash\030\001 \003(\003\022\021\n\tmark_hash\030\002 \003(\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_ChromePerformanceMarkHashes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_ChromePerformanceMarkHashes_descriptor,
        new java.lang.String[] { "SiteHash", "MarkHash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
