// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/common/android_energy_consumer_descriptor.proto

package perfetto.protos;

public final class AndroidEnergyConsumerDescriptorOuterClass {
  private AndroidEnergyConsumerDescriptorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AndroidEnergyConsumerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.AndroidEnergyConsumer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique ID of this energy consumer.  Matches the ID in a
     * AndroidEnergyEstimationBreakdown.
     * </pre>
     *
     * <code>optional int32 energy_consumer_id = 1;</code>
     * @return Whether the energyConsumerId field is set.
     */
    boolean hasEnergyConsumerId();
    /**
     * <pre>
     * Unique ID of this energy consumer.  Matches the ID in a
     * AndroidEnergyEstimationBreakdown.
     * </pre>
     *
     * <code>optional int32 energy_consumer_id = 1;</code>
     * @return The energyConsumerId.
     */
    int getEnergyConsumerId();

    /**
     * <pre>
     * For a group of energy consumers of the same logical type, sorting by
     * ordinal gives their physical order. Ordinals must be consecutive integers
     * starting from 0.
     * </pre>
     *
     * <code>optional int32 ordinal = 2;</code>
     * @return Whether the ordinal field is set.
     */
    boolean hasOrdinal();
    /**
     * <pre>
     * For a group of energy consumers of the same logical type, sorting by
     * ordinal gives their physical order. Ordinals must be consecutive integers
     * starting from 0.
     * </pre>
     *
     * <code>optional int32 ordinal = 2;</code>
     * @return The ordinal.
     */
    int getOrdinal();

    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * Energy consumer based on aidl class:
   * android.hardware.power.stats.EnergyConsumer.
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.AndroidEnergyConsumer}
   */
  public static final class AndroidEnergyConsumer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.AndroidEnergyConsumer)
      AndroidEnergyConsumerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AndroidEnergyConsumer.newBuilder() to construct.
    private AndroidEnergyConsumer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AndroidEnergyConsumer() {
      type_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AndroidEnergyConsumer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.class, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder.class);
    }

    private int bitField0_;
    public static final int ENERGY_CONSUMER_ID_FIELD_NUMBER = 1;
    private int energyConsumerId_ = 0;
    /**
     * <pre>
     * Unique ID of this energy consumer.  Matches the ID in a
     * AndroidEnergyEstimationBreakdown.
     * </pre>
     *
     * <code>optional int32 energy_consumer_id = 1;</code>
     * @return Whether the energyConsumerId field is set.
     */
    @java.lang.Override
    public boolean hasEnergyConsumerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Unique ID of this energy consumer.  Matches the ID in a
     * AndroidEnergyEstimationBreakdown.
     * </pre>
     *
     * <code>optional int32 energy_consumer_id = 1;</code>
     * @return The energyConsumerId.
     */
    @java.lang.Override
    public int getEnergyConsumerId() {
      return energyConsumerId_;
    }

    public static final int ORDINAL_FIELD_NUMBER = 2;
    private int ordinal_ = 0;
    /**
     * <pre>
     * For a group of energy consumers of the same logical type, sorting by
     * ordinal gives their physical order. Ordinals must be consecutive integers
     * starting from 0.
     * </pre>
     *
     * <code>optional int32 ordinal = 2;</code>
     * @return Whether the ordinal field is set.
     */
    @java.lang.Override
    public boolean hasOrdinal() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * For a group of energy consumers of the same logical type, sorting by
     * ordinal gives their physical order. Ordinals must be consecutive integers
     * starting from 0.
     * </pre>
     *
     * <code>optional int32 ordinal = 2;</code>
     * @return The ordinal.
     */
    @java.lang.Override
    public int getOrdinal() {
      return ordinal_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Type of this energy consumer.
     * </pre>
     *
     * <code>optional string type = 3;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Unique name of this energy consumer. Vendor/device specific. Opaque to
     * framework.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, energyConsumerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, ordinal_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, energyConsumerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ordinal_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer)) {
        return super.equals(obj);
      }
      perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer other = (perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer) obj;

      if (hasEnergyConsumerId() != other.hasEnergyConsumerId()) return false;
      if (hasEnergyConsumerId()) {
        if (getEnergyConsumerId()
            != other.getEnergyConsumerId()) return false;
      }
      if (hasOrdinal() != other.hasOrdinal()) return false;
      if (hasOrdinal()) {
        if (getOrdinal()
            != other.getOrdinal()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEnergyConsumerId()) {
        hash = (37 * hash) + ENERGY_CONSUMER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getEnergyConsumerId();
      }
      if (hasOrdinal()) {
        hash = (37 * hash) + ORDINAL_FIELD_NUMBER;
        hash = (53 * hash) + getOrdinal();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Energy consumer based on aidl class:
     * android.hardware.power.stats.EnergyConsumer.
     * </pre>
     *
     * Protobuf type {@code perfetto.protos.AndroidEnergyConsumer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.AndroidEnergyConsumer)
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.class, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder.class);
      }

      // Construct using perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        energyConsumerId_ = 0;
        ordinal_ = 0;
        type_ = "";
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getDefaultInstanceForType() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer build() {
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer buildPartial() {
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer result = new perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.energyConsumerId_ = energyConsumerId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ordinal_ = ordinal_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer) {
          return mergeFrom((perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer other) {
        if (other == perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.getDefaultInstance()) return this;
        if (other.hasEnergyConsumerId()) {
          setEnergyConsumerId(other.getEnergyConsumerId());
        }
        if (other.hasOrdinal()) {
          setOrdinal(other.getOrdinal());
        }
        if (other.hasType()) {
          type_ = other.type_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                energyConsumerId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                ordinal_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                type_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int energyConsumerId_ ;
      /**
       * <pre>
       * Unique ID of this energy consumer.  Matches the ID in a
       * AndroidEnergyEstimationBreakdown.
       * </pre>
       *
       * <code>optional int32 energy_consumer_id = 1;</code>
       * @return Whether the energyConsumerId field is set.
       */
      @java.lang.Override
      public boolean hasEnergyConsumerId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Unique ID of this energy consumer.  Matches the ID in a
       * AndroidEnergyEstimationBreakdown.
       * </pre>
       *
       * <code>optional int32 energy_consumer_id = 1;</code>
       * @return The energyConsumerId.
       */
      @java.lang.Override
      public int getEnergyConsumerId() {
        return energyConsumerId_;
      }
      /**
       * <pre>
       * Unique ID of this energy consumer.  Matches the ID in a
       * AndroidEnergyEstimationBreakdown.
       * </pre>
       *
       * <code>optional int32 energy_consumer_id = 1;</code>
       * @param value The energyConsumerId to set.
       * @return This builder for chaining.
       */
      public Builder setEnergyConsumerId(int value) {
        
        energyConsumerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique ID of this energy consumer.  Matches the ID in a
       * AndroidEnergyEstimationBreakdown.
       * </pre>
       *
       * <code>optional int32 energy_consumer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnergyConsumerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        energyConsumerId_ = 0;
        onChanged();
        return this;
      }

      private int ordinal_ ;
      /**
       * <pre>
       * For a group of energy consumers of the same logical type, sorting by
       * ordinal gives their physical order. Ordinals must be consecutive integers
       * starting from 0.
       * </pre>
       *
       * <code>optional int32 ordinal = 2;</code>
       * @return Whether the ordinal field is set.
       */
      @java.lang.Override
      public boolean hasOrdinal() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * For a group of energy consumers of the same logical type, sorting by
       * ordinal gives their physical order. Ordinals must be consecutive integers
       * starting from 0.
       * </pre>
       *
       * <code>optional int32 ordinal = 2;</code>
       * @return The ordinal.
       */
      @java.lang.Override
      public int getOrdinal() {
        return ordinal_;
      }
      /**
       * <pre>
       * For a group of energy consumers of the same logical type, sorting by
       * ordinal gives their physical order. Ordinals must be consecutive integers
       * starting from 0.
       * </pre>
       *
       * <code>optional int32 ordinal = 2;</code>
       * @param value The ordinal to set.
       * @return This builder for chaining.
       */
      public Builder setOrdinal(int value) {
        
        ordinal_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For a group of energy consumers of the same logical type, sorting by
       * ordinal gives their physical order. Ordinals must be consecutive integers
       * starting from 0.
       * </pre>
       *
       * <code>optional int32 ordinal = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrdinal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ordinal_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of this energy consumer.
       * </pre>
       *
       * <code>optional string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique name of this energy consumer. Vendor/device specific. Opaque to
       * framework.
       * </pre>
       *
       * <code>optional string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.AndroidEnergyConsumer)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidEnergyConsumer)
    private static final perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer();
    }

    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AndroidEnergyConsumer>
        PARSER = new com.google.protobuf.AbstractParser<AndroidEnergyConsumer>() {
      @java.lang.Override
      public AndroidEnergyConsumer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AndroidEnergyConsumer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AndroidEnergyConsumer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AndroidEnergyConsumerDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.AndroidEnergyConsumerDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> 
        getEnergyConsumersList();
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getEnergyConsumers(int index);
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    int getEnergyConsumersCount();
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    java.util.List<? extends perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder> 
        getEnergyConsumersOrBuilderList();
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder getEnergyConsumersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code perfetto.protos.AndroidEnergyConsumerDescriptor}
   */
  public static final class AndroidEnergyConsumerDescriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.AndroidEnergyConsumerDescriptor)
      AndroidEnergyConsumerDescriptorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AndroidEnergyConsumerDescriptor.newBuilder() to construct.
    private AndroidEnergyConsumerDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AndroidEnergyConsumerDescriptor() {
      energyConsumers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AndroidEnergyConsumerDescriptor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.class, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.Builder.class);
    }

    public static final int ENERGY_CONSUMERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> energyConsumers_;
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> getEnergyConsumersList() {
      return energyConsumers_;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder> 
        getEnergyConsumersOrBuilderList() {
      return energyConsumers_;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    @java.lang.Override
    public int getEnergyConsumersCount() {
      return energyConsumers_.size();
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getEnergyConsumers(int index) {
      return energyConsumers_.get(index);
    }
    /**
     * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
     */
    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder getEnergyConsumersOrBuilder(
        int index) {
      return energyConsumers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < energyConsumers_.size(); i++) {
        output.writeMessage(1, energyConsumers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < energyConsumers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, energyConsumers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor)) {
        return super.equals(obj);
      }
      perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor other = (perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor) obj;

      if (!getEnergyConsumersList()
          .equals(other.getEnergyConsumersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEnergyConsumersCount() > 0) {
        hash = (37 * hash) + ENERGY_CONSUMERS_FIELD_NUMBER;
        hash = (53 * hash) + getEnergyConsumersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfetto.protos.AndroidEnergyConsumerDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.AndroidEnergyConsumerDescriptor)
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.class, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.Builder.class);
      }

      // Construct using perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (energyConsumersBuilder_ == null) {
          energyConsumers_ = java.util.Collections.emptyList();
        } else {
          energyConsumers_ = null;
          energyConsumersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor getDefaultInstanceForType() {
        return perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor build() {
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor buildPartial() {
        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor result = new perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor result) {
        if (energyConsumersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            energyConsumers_ = java.util.Collections.unmodifiableList(energyConsumers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.energyConsumers_ = energyConsumers_;
        } else {
          result.energyConsumers_ = energyConsumersBuilder_.build();
        }
      }

      private void buildPartial0(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor) {
          return mergeFrom((perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor other) {
        if (other == perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor.getDefaultInstance()) return this;
        if (energyConsumersBuilder_ == null) {
          if (!other.energyConsumers_.isEmpty()) {
            if (energyConsumers_.isEmpty()) {
              energyConsumers_ = other.energyConsumers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEnergyConsumersIsMutable();
              energyConsumers_.addAll(other.energyConsumers_);
            }
            onChanged();
          }
        } else {
          if (!other.energyConsumers_.isEmpty()) {
            if (energyConsumersBuilder_.isEmpty()) {
              energyConsumersBuilder_.dispose();
              energyConsumersBuilder_ = null;
              energyConsumers_ = other.energyConsumers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              energyConsumersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEnergyConsumersFieldBuilder() : null;
            } else {
              energyConsumersBuilder_.addAllMessages(other.energyConsumers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer m =
                    input.readMessage(
                        perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.PARSER,
                        extensionRegistry);
                if (energyConsumersBuilder_ == null) {
                  ensureEnergyConsumersIsMutable();
                  energyConsumers_.add(m);
                } else {
                  energyConsumersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> energyConsumers_ =
        java.util.Collections.emptyList();
      private void ensureEnergyConsumersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          energyConsumers_ = new java.util.ArrayList<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer>(energyConsumers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder> energyConsumersBuilder_;

      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> getEnergyConsumersList() {
        if (energyConsumersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(energyConsumers_);
        } else {
          return energyConsumersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public int getEnergyConsumersCount() {
        if (energyConsumersBuilder_ == null) {
          return energyConsumers_.size();
        } else {
          return energyConsumersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer getEnergyConsumers(int index) {
        if (energyConsumersBuilder_ == null) {
          return energyConsumers_.get(index);
        } else {
          return energyConsumersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder setEnergyConsumers(
          int index, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer value) {
        if (energyConsumersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnergyConsumersIsMutable();
          energyConsumers_.set(index, value);
          onChanged();
        } else {
          energyConsumersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder setEnergyConsumers(
          int index, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder builderForValue) {
        if (energyConsumersBuilder_ == null) {
          ensureEnergyConsumersIsMutable();
          energyConsumers_.set(index, builderForValue.build());
          onChanged();
        } else {
          energyConsumersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder addEnergyConsumers(perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer value) {
        if (energyConsumersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnergyConsumersIsMutable();
          energyConsumers_.add(value);
          onChanged();
        } else {
          energyConsumersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder addEnergyConsumers(
          int index, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer value) {
        if (energyConsumersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnergyConsumersIsMutable();
          energyConsumers_.add(index, value);
          onChanged();
        } else {
          energyConsumersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder addEnergyConsumers(
          perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder builderForValue) {
        if (energyConsumersBuilder_ == null) {
          ensureEnergyConsumersIsMutable();
          energyConsumers_.add(builderForValue.build());
          onChanged();
        } else {
          energyConsumersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder addEnergyConsumers(
          int index, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder builderForValue) {
        if (energyConsumersBuilder_ == null) {
          ensureEnergyConsumersIsMutable();
          energyConsumers_.add(index, builderForValue.build());
          onChanged();
        } else {
          energyConsumersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder addAllEnergyConsumers(
          java.lang.Iterable<? extends perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer> values) {
        if (energyConsumersBuilder_ == null) {
          ensureEnergyConsumersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, energyConsumers_);
          onChanged();
        } else {
          energyConsumersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder clearEnergyConsumers() {
        if (energyConsumersBuilder_ == null) {
          energyConsumers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          energyConsumersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public Builder removeEnergyConsumers(int index) {
        if (energyConsumersBuilder_ == null) {
          ensureEnergyConsumersIsMutable();
          energyConsumers_.remove(index);
          onChanged();
        } else {
          energyConsumersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder getEnergyConsumersBuilder(
          int index) {
        return getEnergyConsumersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder getEnergyConsumersOrBuilder(
          int index) {
        if (energyConsumersBuilder_ == null) {
          return energyConsumers_.get(index);  } else {
          return energyConsumersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public java.util.List<? extends perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder> 
           getEnergyConsumersOrBuilderList() {
        if (energyConsumersBuilder_ != null) {
          return energyConsumersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(energyConsumers_);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder addEnergyConsumersBuilder() {
        return getEnergyConsumersFieldBuilder().addBuilder(
            perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder addEnergyConsumersBuilder(
          int index) {
        return getEnergyConsumersFieldBuilder().addBuilder(
            index, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.AndroidEnergyConsumer energy_consumers = 1;</code>
       */
      public java.util.List<perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder> 
           getEnergyConsumersBuilderList() {
        return getEnergyConsumersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder> 
          getEnergyConsumersFieldBuilder() {
        if (energyConsumersBuilder_ == null) {
          energyConsumersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumer.Builder, perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerOrBuilder>(
                  energyConsumers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          energyConsumers_ = null;
        }
        return energyConsumersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.AndroidEnergyConsumerDescriptor)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidEnergyConsumerDescriptor)
    private static final perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor();
    }

    public static perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<AndroidEnergyConsumerDescriptor>() {
      @java.lang.Override
      public AndroidEnergyConsumerDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AndroidEnergyConsumerDescriptor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.AndroidEnergyConsumerDescriptorOuterClass.AndroidEnergyConsumerDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_AndroidEnergyConsumer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?protos/perfetto/common/android_energy_" +
      "consumer_descriptor.proto\022\017perfetto.prot" +
      "os\"`\n\025AndroidEnergyConsumer\022\032\n\022energy_co" +
      "nsumer_id\030\001 \001(\005\022\017\n\007ordinal\030\002 \001(\005\022\014\n\004type" +
      "\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\"c\n\037AndroidEnergyCon" +
      "sumerDescriptor\022@\n\020energy_consumers\030\001 \003(" +
      "\0132&.perfetto.protos.AndroidEnergyConsume" +
      "r"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_AndroidEnergyConsumer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_AndroidEnergyConsumer_descriptor,
        new java.lang.String[] { "EnergyConsumerId", "Ordinal", "Type", "Name", });
    internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_AndroidEnergyConsumerDescriptor_descriptor,
        new java.lang.String[] { "EnergyConsumers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
