// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/perfetto/metrics/android/binder_metric.proto

package perfetto.protos;

public final class BinderMetric {
  private BinderMetric() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AndroidBinderMetricOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.AndroidBinderMetric)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> 
        getProcessBreakdownList();
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getProcessBreakdown(int index);
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    int getProcessBreakdownCount();
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    java.util.List<? extends perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder> 
        getProcessBreakdownOrBuilderList();
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder getProcessBreakdownOrBuilder(
        int index);
  }
  /**
   * <pre>
   * This metric provides per-process Binder statistics for traces with binder_driver enabled
   * Specifically, transactions are categorized and counted
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.AndroidBinderMetric}
   */
  public static final class AndroidBinderMetric extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.AndroidBinderMetric)
      AndroidBinderMetricOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AndroidBinderMetric.newBuilder() to construct.
    private AndroidBinderMetric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AndroidBinderMetric() {
      processBreakdown_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AndroidBinderMetric();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              perfetto.protos.BinderMetric.AndroidBinderMetric.class, perfetto.protos.BinderMetric.AndroidBinderMetric.Builder.class);
    }

    public interface PerProcessBreakdownOrBuilder extends
        // @@protoc_insertion_point(interface_extends:perfetto.protos.AndroidBinderMetric.PerProcessBreakdown)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string process_name = 1;</code>
       * @return Whether the processName field is set.
       */
      boolean hasProcessName();
      /**
       * <code>optional string process_name = 1;</code>
       * @return The processName.
       */
      java.lang.String getProcessName();
      /**
       * <code>optional string process_name = 1;</code>
       * @return The bytes for processName.
       */
      com.google.protobuf.ByteString
          getProcessNameBytes();

      /**
       * <code>optional uint32 pid = 2;</code>
       * @return Whether the pid field is set.
       */
      boolean hasPid();
      /**
       * <code>optional uint32 pid = 2;</code>
       * @return The pid.
       */
      int getPid();

      /**
       * <code>optional string slice_name = 3;</code>
       * @return Whether the sliceName field is set.
       */
      boolean hasSliceName();
      /**
       * <code>optional string slice_name = 3;</code>
       * @return The sliceName.
       */
      java.lang.String getSliceName();
      /**
       * <code>optional string slice_name = 3;</code>
       * @return The bytes for sliceName.
       */
      com.google.protobuf.ByteString
          getSliceNameBytes();

      /**
       * <code>optional uint32 count = 4;</code>
       * @return Whether the count field is set.
       */
      boolean hasCount();
      /**
       * <code>optional uint32 count = 4;</code>
       * @return The count.
       */
      int getCount();
    }
    /**
     * Protobuf type {@code perfetto.protos.AndroidBinderMetric.PerProcessBreakdown}
     */
    public static final class PerProcessBreakdown extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:perfetto.protos.AndroidBinderMetric.PerProcessBreakdown)
        PerProcessBreakdownOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PerProcessBreakdown.newBuilder() to construct.
      private PerProcessBreakdown(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PerProcessBreakdown() {
        processName_ = "";
        sliceName_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PerProcessBreakdown();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.class, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder.class);
      }

      private int bitField0_;
      public static final int PROCESS_NAME_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object processName_ = "";
      /**
       * <code>optional string process_name = 1;</code>
       * @return Whether the processName field is set.
       */
      @java.lang.Override
      public boolean hasProcessName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string process_name = 1;</code>
       * @return The processName.
       */
      @java.lang.Override
      public java.lang.String getProcessName() {
        java.lang.Object ref = processName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string process_name = 1;</code>
       * @return The bytes for processName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProcessNameBytes() {
        java.lang.Object ref = processName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PID_FIELD_NUMBER = 2;
      private int pid_ = 0;
      /**
       * <code>optional uint32 pid = 2;</code>
       * @return Whether the pid field is set.
       */
      @java.lang.Override
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 pid = 2;</code>
       * @return The pid.
       */
      @java.lang.Override
      public int getPid() {
        return pid_;
      }

      public static final int SLICE_NAME_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object sliceName_ = "";
      /**
       * <code>optional string slice_name = 3;</code>
       * @return Whether the sliceName field is set.
       */
      @java.lang.Override
      public boolean hasSliceName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string slice_name = 3;</code>
       * @return The sliceName.
       */
      @java.lang.Override
      public java.lang.String getSliceName() {
        java.lang.Object ref = sliceName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sliceName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string slice_name = 3;</code>
       * @return The bytes for sliceName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSliceNameBytes() {
        java.lang.Object ref = sliceName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sliceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COUNT_FIELD_NUMBER = 4;
      private int count_ = 0;
      /**
       * <code>optional uint32 count = 4;</code>
       * @return Whether the count field is set.
       */
      @java.lang.Override
      public boolean hasCount() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 count = 4;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, processName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeUInt32(2, pid_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sliceName_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeUInt32(4, count_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, processName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, pid_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sliceName_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, count_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown)) {
          return super.equals(obj);
        }
        perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown other = (perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown) obj;

        if (hasProcessName() != other.hasProcessName()) return false;
        if (hasProcessName()) {
          if (!getProcessName()
              .equals(other.getProcessName())) return false;
        }
        if (hasPid() != other.hasPid()) return false;
        if (hasPid()) {
          if (getPid()
              != other.getPid()) return false;
        }
        if (hasSliceName() != other.hasSliceName()) return false;
        if (hasSliceName()) {
          if (!getSliceName()
              .equals(other.getSliceName())) return false;
        }
        if (hasCount() != other.hasCount()) return false;
        if (hasCount()) {
          if (getCount()
              != other.getCount()) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasProcessName()) {
          hash = (37 * hash) + PROCESS_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getProcessName().hashCode();
        }
        if (hasPid()) {
          hash = (37 * hash) + PID_FIELD_NUMBER;
          hash = (53 * hash) + getPid();
        }
        if (hasSliceName()) {
          hash = (37 * hash) + SLICE_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getSliceName().hashCode();
        }
        if (hasCount()) {
          hash = (37 * hash) + COUNT_FIELD_NUMBER;
          hash = (53 * hash) + getCount();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code perfetto.protos.AndroidBinderMetric.PerProcessBreakdown}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:perfetto.protos.AndroidBinderMetric.PerProcessBreakdown)
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.class, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder.class);
        }

        // Construct using perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          processName_ = "";
          pid_ = 0;
          sliceName_ = "";
          count_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor;
        }

        @java.lang.Override
        public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getDefaultInstanceForType() {
          return perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.getDefaultInstance();
        }

        @java.lang.Override
        public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown build() {
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown buildPartial() {
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown result = new perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.processName_ = processName_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.pid_ = pid_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.sliceName_ = sliceName_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.count_ = count_;
            to_bitField0_ |= 0x00000008;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown) {
            return mergeFrom((perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown other) {
          if (other == perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.getDefaultInstance()) return this;
          if (other.hasProcessName()) {
            processName_ = other.processName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.hasPid()) {
            setPid(other.getPid());
          }
          if (other.hasSliceName()) {
            sliceName_ = other.sliceName_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          if (other.hasCount()) {
            setCount(other.getCount());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  processName_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 16: {
                  pid_ = input.readUInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                case 26: {
                  sliceName_ = input.readBytes();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 32: {
                  count_ = input.readUInt32();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 32
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object processName_ = "";
        /**
         * <code>optional string process_name = 1;</code>
         * @return Whether the processName field is set.
         */
        public boolean hasProcessName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string process_name = 1;</code>
         * @return The processName.
         */
        public java.lang.String getProcessName() {
          java.lang.Object ref = processName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              processName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string process_name = 1;</code>
         * @return The bytes for processName.
         */
        public com.google.protobuf.ByteString
            getProcessNameBytes() {
          java.lang.Object ref = processName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            processName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string process_name = 1;</code>
         * @param value The processName to set.
         * @return This builder for chaining.
         */
        public Builder setProcessName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          processName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional string process_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearProcessName() {
          processName_ = getDefaultInstance().getProcessName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>optional string process_name = 1;</code>
         * @param value The bytes for processName to set.
         * @return This builder for chaining.
         */
        public Builder setProcessNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          processName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private int pid_ ;
        /**
         * <code>optional uint32 pid = 2;</code>
         * @return Whether the pid field is set.
         */
        @java.lang.Override
        public boolean hasPid() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional uint32 pid = 2;</code>
         * @return The pid.
         */
        @java.lang.Override
        public int getPid() {
          return pid_;
        }
        /**
         * <code>optional uint32 pid = 2;</code>
         * @param value The pid to set.
         * @return This builder for chaining.
         */
        public Builder setPid(int value) {
          
          pid_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 pid = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPid() {
          bitField0_ = (bitField0_ & ~0x00000002);
          pid_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object sliceName_ = "";
        /**
         * <code>optional string slice_name = 3;</code>
         * @return Whether the sliceName field is set.
         */
        public boolean hasSliceName() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string slice_name = 3;</code>
         * @return The sliceName.
         */
        public java.lang.String getSliceName() {
          java.lang.Object ref = sliceName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              sliceName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string slice_name = 3;</code>
         * @return The bytes for sliceName.
         */
        public com.google.protobuf.ByteString
            getSliceNameBytes() {
          java.lang.Object ref = sliceName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sliceName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string slice_name = 3;</code>
         * @param value The sliceName to set.
         * @return This builder for chaining.
         */
        public Builder setSliceName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          sliceName_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>optional string slice_name = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearSliceName() {
          sliceName_ = getDefaultInstance().getSliceName();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>optional string slice_name = 3;</code>
         * @param value The bytes for sliceName to set.
         * @return This builder for chaining.
         */
        public Builder setSliceNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          sliceName_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }

        private int count_ ;
        /**
         * <code>optional uint32 count = 4;</code>
         * @return Whether the count field is set.
         */
        @java.lang.Override
        public boolean hasCount() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional uint32 count = 4;</code>
         * @return The count.
         */
        @java.lang.Override
        public int getCount() {
          return count_;
        }
        /**
         * <code>optional uint32 count = 4;</code>
         * @param value The count to set.
         * @return This builder for chaining.
         */
        public Builder setCount(int value) {
          
          count_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 count = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearCount() {
          bitField0_ = (bitField0_ & ~0x00000008);
          count_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:perfetto.protos.AndroidBinderMetric.PerProcessBreakdown)
      }

      // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidBinderMetric.PerProcessBreakdown)
      private static final perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown();
      }

      public static perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<PerProcessBreakdown>
          PARSER = new com.google.protobuf.AbstractParser<PerProcessBreakdown>() {
        @java.lang.Override
        public PerProcessBreakdown parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<PerProcessBreakdown> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PerProcessBreakdown> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PROCESS_BREAKDOWN_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> processBreakdown_;
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    @java.lang.Override
    public java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> getProcessBreakdownList() {
      return processBreakdown_;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder> 
        getProcessBreakdownOrBuilderList() {
      return processBreakdown_;
    }
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    @java.lang.Override
    public int getProcessBreakdownCount() {
      return processBreakdown_.size();
    }
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    @java.lang.Override
    public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getProcessBreakdown(int index) {
      return processBreakdown_.get(index);
    }
    /**
     * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
     */
    @java.lang.Override
    public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder getProcessBreakdownOrBuilder(
        int index) {
      return processBreakdown_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < processBreakdown_.size(); i++) {
        output.writeMessage(1, processBreakdown_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < processBreakdown_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, processBreakdown_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof perfetto.protos.BinderMetric.AndroidBinderMetric)) {
        return super.equals(obj);
      }
      perfetto.protos.BinderMetric.AndroidBinderMetric other = (perfetto.protos.BinderMetric.AndroidBinderMetric) obj;

      if (!getProcessBreakdownList()
          .equals(other.getProcessBreakdownList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProcessBreakdownCount() > 0) {
        hash = (37 * hash) + PROCESS_BREAKDOWN_FIELD_NUMBER;
        hash = (53 * hash) + getProcessBreakdownList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static perfetto.protos.BinderMetric.AndroidBinderMetric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(perfetto.protos.BinderMetric.AndroidBinderMetric prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This metric provides per-process Binder statistics for traces with binder_driver enabled
     * Specifically, transactions are categorized and counted
     * </pre>
     *
     * Protobuf type {@code perfetto.protos.AndroidBinderMetric}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.AndroidBinderMetric)
        perfetto.protos.BinderMetric.AndroidBinderMetricOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                perfetto.protos.BinderMetric.AndroidBinderMetric.class, perfetto.protos.BinderMetric.AndroidBinderMetric.Builder.class);
      }

      // Construct using perfetto.protos.BinderMetric.AndroidBinderMetric.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (processBreakdownBuilder_ == null) {
          processBreakdown_ = java.util.Collections.emptyList();
        } else {
          processBreakdown_ = null;
          processBreakdownBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return perfetto.protos.BinderMetric.internal_static_perfetto_protos_AndroidBinderMetric_descriptor;
      }

      @java.lang.Override
      public perfetto.protos.BinderMetric.AndroidBinderMetric getDefaultInstanceForType() {
        return perfetto.protos.BinderMetric.AndroidBinderMetric.getDefaultInstance();
      }

      @java.lang.Override
      public perfetto.protos.BinderMetric.AndroidBinderMetric build() {
        perfetto.protos.BinderMetric.AndroidBinderMetric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public perfetto.protos.BinderMetric.AndroidBinderMetric buildPartial() {
        perfetto.protos.BinderMetric.AndroidBinderMetric result = new perfetto.protos.BinderMetric.AndroidBinderMetric(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(perfetto.protos.BinderMetric.AndroidBinderMetric result) {
        if (processBreakdownBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            processBreakdown_ = java.util.Collections.unmodifiableList(processBreakdown_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.processBreakdown_ = processBreakdown_;
        } else {
          result.processBreakdown_ = processBreakdownBuilder_.build();
        }
      }

      private void buildPartial0(perfetto.protos.BinderMetric.AndroidBinderMetric result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof perfetto.protos.BinderMetric.AndroidBinderMetric) {
          return mergeFrom((perfetto.protos.BinderMetric.AndroidBinderMetric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(perfetto.protos.BinderMetric.AndroidBinderMetric other) {
        if (other == perfetto.protos.BinderMetric.AndroidBinderMetric.getDefaultInstance()) return this;
        if (processBreakdownBuilder_ == null) {
          if (!other.processBreakdown_.isEmpty()) {
            if (processBreakdown_.isEmpty()) {
              processBreakdown_ = other.processBreakdown_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProcessBreakdownIsMutable();
              processBreakdown_.addAll(other.processBreakdown_);
            }
            onChanged();
          }
        } else {
          if (!other.processBreakdown_.isEmpty()) {
            if (processBreakdownBuilder_.isEmpty()) {
              processBreakdownBuilder_.dispose();
              processBreakdownBuilder_ = null;
              processBreakdown_ = other.processBreakdown_;
              bitField0_ = (bitField0_ & ~0x00000001);
              processBreakdownBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProcessBreakdownFieldBuilder() : null;
            } else {
              processBreakdownBuilder_.addAllMessages(other.processBreakdown_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown m =
                    input.readMessage(
                        perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.PARSER,
                        extensionRegistry);
                if (processBreakdownBuilder_ == null) {
                  ensureProcessBreakdownIsMutable();
                  processBreakdown_.add(m);
                } else {
                  processBreakdownBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> processBreakdown_ =
        java.util.Collections.emptyList();
      private void ensureProcessBreakdownIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          processBreakdown_ = new java.util.ArrayList<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown>(processBreakdown_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder> processBreakdownBuilder_;

      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> getProcessBreakdownList() {
        if (processBreakdownBuilder_ == null) {
          return java.util.Collections.unmodifiableList(processBreakdown_);
        } else {
          return processBreakdownBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public int getProcessBreakdownCount() {
        if (processBreakdownBuilder_ == null) {
          return processBreakdown_.size();
        } else {
          return processBreakdownBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown getProcessBreakdown(int index) {
        if (processBreakdownBuilder_ == null) {
          return processBreakdown_.get(index);
        } else {
          return processBreakdownBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder setProcessBreakdown(
          int index, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown value) {
        if (processBreakdownBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProcessBreakdownIsMutable();
          processBreakdown_.set(index, value);
          onChanged();
        } else {
          processBreakdownBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder setProcessBreakdown(
          int index, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder builderForValue) {
        if (processBreakdownBuilder_ == null) {
          ensureProcessBreakdownIsMutable();
          processBreakdown_.set(index, builderForValue.build());
          onChanged();
        } else {
          processBreakdownBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder addProcessBreakdown(perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown value) {
        if (processBreakdownBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProcessBreakdownIsMutable();
          processBreakdown_.add(value);
          onChanged();
        } else {
          processBreakdownBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder addProcessBreakdown(
          int index, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown value) {
        if (processBreakdownBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProcessBreakdownIsMutable();
          processBreakdown_.add(index, value);
          onChanged();
        } else {
          processBreakdownBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder addProcessBreakdown(
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder builderForValue) {
        if (processBreakdownBuilder_ == null) {
          ensureProcessBreakdownIsMutable();
          processBreakdown_.add(builderForValue.build());
          onChanged();
        } else {
          processBreakdownBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder addProcessBreakdown(
          int index, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder builderForValue) {
        if (processBreakdownBuilder_ == null) {
          ensureProcessBreakdownIsMutable();
          processBreakdown_.add(index, builderForValue.build());
          onChanged();
        } else {
          processBreakdownBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder addAllProcessBreakdown(
          java.lang.Iterable<? extends perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown> values) {
        if (processBreakdownBuilder_ == null) {
          ensureProcessBreakdownIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, processBreakdown_);
          onChanged();
        } else {
          processBreakdownBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder clearProcessBreakdown() {
        if (processBreakdownBuilder_ == null) {
          processBreakdown_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          processBreakdownBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public Builder removeProcessBreakdown(int index) {
        if (processBreakdownBuilder_ == null) {
          ensureProcessBreakdownIsMutable();
          processBreakdown_.remove(index);
          onChanged();
        } else {
          processBreakdownBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder getProcessBreakdownBuilder(
          int index) {
        return getProcessBreakdownFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder getProcessBreakdownOrBuilder(
          int index) {
        if (processBreakdownBuilder_ == null) {
          return processBreakdown_.get(index);  } else {
          return processBreakdownBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public java.util.List<? extends perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder> 
           getProcessBreakdownOrBuilderList() {
        if (processBreakdownBuilder_ != null) {
          return processBreakdownBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(processBreakdown_);
        }
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder addProcessBreakdownBuilder() {
        return getProcessBreakdownFieldBuilder().addBuilder(
            perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder addProcessBreakdownBuilder(
          int index) {
        return getProcessBreakdownFieldBuilder().addBuilder(
            index, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.AndroidBinderMetric.PerProcessBreakdown process_breakdown = 1;</code>
       */
      public java.util.List<perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder> 
           getProcessBreakdownBuilderList() {
        return getProcessBreakdownFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder> 
          getProcessBreakdownFieldBuilder() {
        if (processBreakdownBuilder_ == null) {
          processBreakdownBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdown.Builder, perfetto.protos.BinderMetric.AndroidBinderMetric.PerProcessBreakdownOrBuilder>(
                  processBreakdown_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          processBreakdown_ = null;
        }
        return processBreakdownBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:perfetto.protos.AndroidBinderMetric)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.AndroidBinderMetric)
    private static final perfetto.protos.BinderMetric.AndroidBinderMetric DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new perfetto.protos.BinderMetric.AndroidBinderMetric();
    }

    public static perfetto.protos.BinderMetric.AndroidBinderMetric getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AndroidBinderMetric>
        PARSER = new com.google.protobuf.AbstractParser<AndroidBinderMetric>() {
      @java.lang.Override
      public AndroidBinderMetric parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AndroidBinderMetric> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AndroidBinderMetric> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public perfetto.protos.BinderMetric.AndroidBinderMetric getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_AndroidBinderMetric_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_AndroidBinderMetric_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3protos/perfetto/metrics/android/binder" +
      "_metric.proto\022\017perfetto.protos\"\307\001\n\023Andro" +
      "idBinderMetric\022S\n\021process_breakdown\030\001 \003(" +
      "\01328.perfetto.protos.AndroidBinderMetric." +
      "PerProcessBreakdown\032[\n\023PerProcessBreakdo" +
      "wn\022\024\n\014process_name\030\001 \001(\t\022\013\n\003pid\030\002 \001(\r\022\022\n" +
      "\nslice_name\030\003 \001(\t\022\r\n\005count\030\004 \001(\r"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_perfetto_protos_AndroidBinderMetric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_AndroidBinderMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_AndroidBinderMetric_descriptor,
        new java.lang.String[] { "ProcessBreakdown", });
    internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor =
      internal_static_perfetto_protos_AndroidBinderMetric_descriptor.getNestedTypes().get(0);
    internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_perfetto_protos_AndroidBinderMetric_PerProcessBreakdown_descriptor,
        new java.lang.String[] { "ProcessName", "Pid", "SliceName", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
